### ISSUE TITLE
Insert images into presentation ?

### ISSUE THREAD

**Issue by larabih** [tajpure/vortex#2]
I tried to insert an image with the usual markdown syntax but no image inserted . Is there a specific syntax to insert an image?

Thanks for Vortex.

**Comment by tajpure** [comment]
No specific syntax to insert an image, maybe your image path is wrong. You can just drag the image into the text area,  and the image will be inserted.

**Comment by larabih** [comment]
Ah Ok, thank you.
I used a relative path instead of the absolute one. Now, the image is correctly inserted.
