### ISSUE TITLE
Would you consider support markdown-plus?

### ISSUE THREAD

**Issue by fduxiao** [tajpure/vortex#4]
[MarkdownPlus](http://mdp.tylingsoft.com/) won't be too difficult to implement.
It will be excellent if you could add an `export to pdf` for the whole page besides ppt only.
Also, if you could give the contribution guide and developing docs, I'd like to make a pull request.

**Comment by tajpure** [comment]
This editor integrated with Chart.js looks good, I will consider adding chart as a feature.
